### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by DooDip** [dantheman213/reddit-post-crawler-video-generator#7]
Hello, when I try to run (for example)
`docker run --name rpcvg -d -v /opt/rpcvg/sources:/data -v /opt/rpcvg/output:/output rpcvg:latest https://www.reddit.com/r/BetterEveryLoop/top/?t=year`

I get

`  
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
main.main()
	/usr/local/main.go:47 +0x20e2
exit status 2`

very briefly and then the container disappears. I've also tried
`docker run -d --name rpcvg \
    -v /media/docker/rpcvg/cache:/cache \
    -v /media/docker/rpcvg/sources:/data \
    -v /media/docker/rpcvg/output:/output \
    dantheman213/rpcvg:latest \
    gifs,month`

**Comment by dantheman213** [comment]
I just updated master branch with latest tags. Please try again.

**Comment by dantheman213** [comment]
I updated DockerHub with the latest version of what's in Github master. It should work now. Some subreddits may have individual issues btw. I just tried about a dozen different ones and they all worked for me. 

Please try again and let me know if that resolved your issue.

```
docker run -d --name rpcvg -v /media/docker/rpcvg/cache:/cache -v /media/docker/rpcvg/sources:/data -v /media/docker/rpcvg/output:/output dantheman213/rpcvg:latest gifs,month
```
